server:
 port: 8080

spring:
  application:
    name: accounts
    
  profiles:
   active: "prod"

  datasource:
    url: jdbc:mysql://localhost:3306/eazybankapp
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
   import: "optional:configserver:http://localhost:8071/"
 
